=== Vince0931/parcoursdesoins/RDF4J/rdf4j-getting-started/query/eventslinks.dtd
<!ELEMENT eventslinks (event+, link*)>
<!ELEMENT event (eventType,predicate*)>
<!ATTLIST event number CDATA #REQUIRED>
<!ELEMENT eventType (#PCDATA)>
<!ELEMENT predicate (numeric|factor|date)>

<!ELEMENT numeric (predicateType, minValue, maxValue)>
<!ELEMENT date (predicateType, minValue, maxValue)>
<!ELEMENT predicateType (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>

<!ELEMENT factor (predicateType, value+)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT link (event1,event2,predicate1,predicate2,operator,minValue,maxValue)>
<!ELEMENT event1 (#PCDATA)>
<!ELEMENT event2 (#PCDATA)>
<!ELEMENT predicate1 (#PCDATA)>
<!ELEMENT predicate2 (#PCDATA)>
<!ELEMENT operator (#PCDATA)>

=== Vince0931/parcoursdesoins/server/V5/sunburst/test.xml
<?xml version="1.0"?>
<!DOCTYPE eventslinks SYSTEM "eventslinks.dtd" > 
<eventslinks>
 <event number="0">
  
  <eventType>SejourMCO</eventType>
  <predicate>
   <factor>
    <predicateType>inEtab</predicateType>
    <value>1</value>
    <value>2</value>
    <value>3</value>
    <value>4</value>
    <value>5</value>
    <value>6</value>
    <value>7</value>
    <value>8</value>
    <value>9</value>
    <value>10</value>
   </factor>
  </predicate>
  <predicate>
   <Date>
    <predicateType>hasEnd</predicateType>
    <minValue>10</minValue>
    <maxValue>20</maxValue>
   </Date>
  </predicate>
 </event>
 <event number="1">
  
  <eventType>SejourSSR</eventType>
  <predicate>
   <numeric>
    <predicateType>hasMedecin</predicateType>
    <minValue>10</minValue>
    <maxValue>20</maxValue>
   </numeric>
  </predicate>
 </event>
</eventslinks>
