=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/describe.dtd
<!ELEMENT eventslinks (event, context)>
<!ELEMENT event (terminologyName, eventType,predicate, value)>
<!ELEMENT terminologyName (#PCDATA)>
<!ELEMENT eventType (#PCDATA)>
<!ELEMENT predicate (predicateType)>
<!ELEMENT predicateType (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT context (value)>

=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/testDescribe.xml
<?xml version="1.0"?>
<!DOCTYPE eventslinks SYSTEM "describe.dtd" > 
<eventslinks>
 <event>
  <eventType>SejourMCO</eventType>
  <predicate>
   <predicateType>inEtab	hasBeginning	hasEnd</predicateType>
  </predicate>
  <value>p1_SejourMCO_2009_11_21T02_08_00_000_01_00	p10_SejourMCO_2009_10_06T04_32_00_000_02_00</value>
 </event>
 <context>
  <value>p1	p10</value>
 </context>
</eventslinks>

=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/describeMCO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventslinks SYSTEM "describe.dtd">
<eventslinks>
	<event number="0">
		<eventType>SejourMCO</eventType>
		<predicate>
		<predicateType>inEtab</predicateType>
		</predicate>
		<value>p1_SejourMCO_2009_11_21T02_08_00_000_01_00	p10_SejourMCO_2009_10_06T04_32_00_000_02_00</value>
	</event>
	
	<context>
	<value>p1	p10</value>
	</context>
</eventslinks>
