=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/eventslinks.dtd
<!ELEMENT eventslinks (event+, link*, context?)>
<!ELEMENT event (terminologyName, eventType,predicate*)>
<!ATTLIST event number CDATA #REQUIRED>
<!ELEMENT terminologyName (#PCDATA)>
<!ELEMENT eventType (#PCDATA)>
<!ELEMENT predicate (numeric|factor|date)>

<!ELEMENT numeric (predicateType, minValue, maxValue)>
<!ELEMENT date (predicateType, minValue, maxValue)>
<!ELEMENT predicateType (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>

<!ELEMENT factor (predicateType, value+)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT link (event1,event2,predicate1,predicate2,operator,minValue,maxValue)>
<!ELEMENT event1 (#PCDATA)>
<!ELEMENT event2 (#PCDATA)>
<!ELEMENT predicate1 (#PCDATA)>
<!ELEMENT predicate2 (#PCDATA)>
<!ELEMENT operator (#PCDATA)>

<!ELEMENT context (value)>

=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/searchContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventslinks SYSTEM "eventslinks.dtd">
<eventslinks>
	<event number="0">
		<terminologyName>Graph</terminologyName>
		<eventType>Graph</eventType>
		<predicate>
			<factor>
				<predicateType>CatAge</predicateType>
				<value>18-75	+75</value>
			</factor>
		</predicate>
	</event>
</eventslinks>

=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventslinks SYSTEM "eventslinks.dtd">
<eventslinks>
	<event number="0">
		<eventType>SejourMCO</eventType>
		<predicate>
			<numeric>
				<predicateType>hasMedecin</predicateType>
				<minValue>10</minValue>
				<maxValue>20</maxValue>
			</numeric>
		</predicate>
		<predicate>
			<factor>
				<predicateType>hasDP</predicateType>
				<value>15115457</value>
				<value>45656244</value>
				<value>1</value>
				<value>2</value>
				<value>pellegrin</value>
			</factor>
		</predicate>	
	</event>
		<event number="1">
		<eventType>SejourMCO</eventType>
		<predicate>
			<numeric>
				<predicateType>hasMedecin</predicateType>
				<minValue>10</minValue>
				<maxValue>20</maxValue>
			</numeric>
		</predicate>	
	</event>
	<link>
		<event1>1</event1>
		<event2>0</event2>
		<predicate1>hasBeginning</predicate1>
		<predicate2>hasMedecin</predicate2>
		<operator>diff</operator>
		<minValue>1</minValue>
		<maxValue>10</maxValue>
	</link>
</eventslinks>

=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/queryMCOSSR3day.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventslinks SYSTEM "eventslinks.dtd">
<eventslinks>
	<event number="0">
		<eventType>SejourMCO</eventType>	
		<predicate>
			<factor>
					<predicateType>inEtab</predicateType>
					<value>330000555</value>
					<value>330000217</value>
			</factor>
		</predicate>
	</event>
		<event number="1">
		<eventType>SejourSSR</eventType>
		
	</event>
		<link>
		<event1>0</event1>
		<event2>1</event2>
		<predicate1>hasEnd</predicate1>
		<predicate2>hasBeginning</predicate2>
		<operator>diff</operator>
		<minValue>1</minValue>
		<maxValue>3</maxValue>
	</link>
</eventslinks>

=== Vince0931/parcoursdesoins/RDF4J/rdf4j-parcours/src/main/resources/query/queryMCOSSRafter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eventslinks SYSTEM "eventslinks.dtd">
<eventslinks>
	<event number="0">
		<eventType>SejourMCO</eventType>	
	</event>
		<event number="1">
		<eventType>SejourMCO</eventType>	
	</event>
		<link>
		<event1>0</event1>
		<event2>1</event2>
		<predicate1>hasEnd</predicate1>
		<predicate2>hasBeginning</predicate2>
		<operator>diff</operator>
		<minValue>0</minValue>
		<maxValue></maxValue>
	</link>
</eventslinks>
